module.exports = [
"Tell me about a situation where you had a conflict with someone on your team. What was it about? What did you do? How did they react? What was the outcome?",
"Give an example of when you saw a peer struggling and decided to step in and help. What was the situation and what actions did you take? What was the outcome?",
"Tell me about a time you committed a mistake?",
"Tell me about a time when your earned your teammate's trust?",
"Tell me about a time when you couldn't meet your deadline?",
"Tell me about a time when your teammate didn't agree with you? What did you do?",
"Tell me about a time when you invented something?",
"Tell me about a time when you took important decision without any data?",
"Tell me about a time when you helped one of your teammates?",
"Have you ever been in a situation where you had to make a choice among a few options, but did not have a lot of time to explore each option",
"Have you ever failed at something? What did you learn from it?",
"name a time when you went out of your way to help someone?",
"Have you ever received negative feedback from manager and how you responded.",
"When was a time when you did not have enough data and had to use judgement to make decision.",
"Has there been a time when you helped someone grow in career and it benefited them.",
"Has there been a time when you helped someone grow but did not benefit them.",
"What was a time when you were 75% through a project and realized you had the wrong goal.",
"Tell me about yourself. Tell me about a project you're working on.",
"Tell me about a time you had to help a team member struggling with a task.",
"Tell me about a time you faced an obstacle and how you overcame it.",
"Tell me about one of your projects?",
"Tell me a time you took some on some risk",
"Have you ever had to make a tough decision without consulting anybody?", 
"Tell me about a time when you took a decision on your own without the manager's prior approval",
"Tell me about a time you had multiple solutions and you had to select an optimal one",
"Tell me about a time when you innovated and exceeded the expectation",
"Tell me about a time where you had to make a decision based on limited information and how it impacted the outcome.",
"Tell me about a time when you had to face tight time constraints during a project.",
"Tell me about a time when you had conflicting ideas with your teammates and how did you resolve them?",
"What is a project you're proud of?",
"Tell me about a time when you felt under pressure that you wouldn't be able to get something done or had to take a pivot at the last minute"
];
